// <auto-generated />
using System;
using HeThongNhaSach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongNhaSach.Migrations
{
    [DbContext(typeof(NhaSachContext))]
    [Migration("20250922123131_FixTacGia")]
    partial class FixTacGia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongNhaSach.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCtdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtdh"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<int?>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int?>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCtdh")
                        .HasName("PK__ChiTietD__1E4E40F0FA9A5C98");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDm"));

                    b.Property<string>("TenDm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDM");

                    b.HasKey("MaDm")
                        .HasName("PK__DanhMuc__2725866EF6F3D02E");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xử lý");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__272586612801CCE0");

                    b.HasIndex("MaTk");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1EDE862225");

                    b.HasIndex("MaTk");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<int?>("GiamGia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaDm")
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("SoSao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 1)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C88F41661");

                    b.HasIndex("MaDm");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("KhachHang");

                    b.HasKey("MaTk")
                        .HasName("PK__TaiKhoan__2725007062D737FC");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D10534BB2ACE8C")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("HeThongNhaSach.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .HasConstraintName("FK__ChiTietDon__MaDH__656C112C");

                    b.HasOne("HeThongNhaSach.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__ChiTietDon__MaSP__66603565");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.DonHang", b =>
                {
                    b.HasOne("HeThongNhaSach.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__DonHang__MaTK__60A75C0F");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.KhachHang", b =>
                {
                    b.HasOne("HeThongNhaSach.Models.TaiKhoan", "MaTkNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__KhachHang__MaTK__6A30C649");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.SanPham", b =>
                {
                    b.HasOne("HeThongNhaSach.Models.DanhMuc", "MaDmNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDm")
                        .HasConstraintName("FK__SanPham__MaDM__59FA5E80");

                    b.Navigation("MaDmNavigation");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("HeThongNhaSach.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
